### ISSUE TITLE
$aaguid = $this->webauthn->register()->aaguid(json_encode($data)); throws error

### ISSUE THREAD

**Issue by mathewparet** [svgta1/webauthn-php#1]
I get the below error:

```
Webauthn\ Exception \ InvalidDataException Unable to load the data
```
when running

```
$aaguid = $this->webauthn->register()->aaguid($data);
```

Here `$data` is

```json
{
  "id": "cUFLLflzEGgpPTa4KypsCiE2XGPQ25vZE62vMMHDemY",
  "rawId": "cUFLLflzEGgpPTa4KypsCiE2XGPQ25vZE62vMMHDemY",
  "response": {
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFAAAAAK3OAAI1vMYKZIsLJfHwVQMAIHFBSy35cxBoKT02uCsqbAohNlxj0Nub2ROtrzDBw3pmpQECAyYgASFYIO2E2RtO8g3sKfDI_g_xPEpQvFC75pZXEGGZAUM__k7GIlggxJiyTzoh_ngPFyWewrwRnJPZLC0lJc8tUbHhTHiJM6M",
    "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiQ0xSa09PN05WQ3RvRWZTbXl3Q2dZd19Da0hXYVluVlBPaHVTZzNyS3hXcWpubGotakNRWWoxSmRtcHJRNmVvdUVDQ0N5clBEQmVObG9EMEVLSDItdHciLCJvcmlnaW4iOiJodHRwOi8vbG9jYWxob3N0IiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ",
    "transports": [
      "internal"
    ],
    "publicKeyAlgorithm": -7,
    "publicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7YTZG07yDewp8Mj-D_E8SlC8ULvmllcQYZkBQz_-TsbEmLJPOiH-eA8XJZ7CvBGck9ksLSUlzy1RseFMeIkzow",
    "authenticatorData": "SZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFAAAAAK3OAAI1vMYKZIsLJfHwVQMAIHFBSy35cxBoKT02uCsqbAohNlxj0Nub2ROtrzDBw3pmpQECAyYgASFYIO2E2RtO8g3sKfDI_g_xPEpQvFC75pZXEGGZAUM__k7GIlggxJiyTzoh_ngPFyWewrwRnJPZLC0lJc8tUbHhTHiJM6M"
  },
  "type": "public-key",
  "clientExtensionResults": [],
  "authenticatorAttachment": "platform"
}
```

The options json sent by the server was:

```json
{
  "rp": {
    "name": "TeslaStats",
    "icon": "data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"100\" height=\"100\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"#4F46E5\"/><rect x=\"8\" y=\"6\" width=\"8\" height=\"4\" fill=\"#FFFFFF\"/><rect x=\"9\" y=\"10\" width=\"6\" height=\"5\" fill=\"#FFFFFF\"/><path d=\"M8 15h8v2H8z\" fill=\"#FFFFFF\"/></svg>",
    "id": "localhost"
  },
  "user": {
    "name": "mathewparet@gmail.com",
    "id": "MQ",
    "displayName": "Mathew"
  },
  "challenge": "CLRkOO7NVCtoEfSmywCgYw_CkHWaYnVPOhuSg3rKxWqjnlj-jCQYj1JdmprQ6eouECCCyrPDBeNloD0EKH2-tw",
  "pubKeyCredParams": [
    {
      "type": "public-key",
      "alg": -7
    },
    {
      "type": "public-key",
      "alg": -257
    }
  ],
  "timeout": 300000,
  "authenticatorSelection": {
    "requireResidentKey": false,
    "userVerification": "preferred",
    "residentKey": "preferred"
  },
  "attestation": "none"
}
```

**Comment by svgta1** [comment]
Hello,

Can you verify your using the 1.0.2 version with composer ? Or do a composer update ?

**Comment by mathewparet** [comment]
I am using `Composer version 2.7.1 2024-02-09 15:26:28`.

But once I removed this package and webauthn package (which I had already installed) and re-installed this package it worked.

However, it seems like it doesn't work with everything:
1. Chrome Profile based passkey - ✅ 
2. Macbook Touch ID - ✅ 
3. Enpass Password Manager based passkey - ❌ 
4. Using phone to authenticate when the website is open on the phone browser - ✅ 
5. Using phone to authenticate when triggered from laptop - That is by selecting my android device on the create passkey screen presented by chrome - ❌ 

*When using the 4th option, android starts with the activity but after sometime shows "Something went wrong".*

`Undefined property: stdClass::$publicKeyAlgorithm` when calling `$this->webauthn->register()->validate()`.

Error is at `vendor/svgta/webauthn/lib/register.php:118`
 
This is the data received by the server when Enpass password manager generated the passkey and sent:

```json
{
        "id": "OXAvgXIn7w2m1DQ-udr6simqtT_DK76dZr3L6WH7hL0",
        "rawId": "OXAvgXIn7w2m1DQ-udr6simqtT_DK76dZr3L6WH7hL0",
        "response": {
            "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikrfib3PjzQH9ab0yDXhjFR6LN1Un-cXd32vJpl6_yc5tJAAAAAPOAlUB_FEnBqLOPgTsiVUEAIDlwL4FyJ-8NptQ0Prna-rIpqrU_wyu-nWa9y-lh-4S9pQECAyYgASFYIHPnYEqC9EQ9SN1cPmBRZF6ZxpsxvLUM9bvyQUQayazSIlggB1UYw1zeX7wQzmsLp5tgyCxXCWcf95I7Sr0Y1s77TOs",
            "clientDataJSON": "eyJ0eXBlIjogIndlYmF1dGhuLmNyZWF0ZSIsICJjaGFsbGVuZ2UiOiAiRk9VQXhpREh0MHQ2Sm5TQWdaQWVKZ2RIVE9vSW5CUHdBLWZnQ2xydURBcDVoejQ3M3FqSGx1MFFOMFNKV0VKamZua3pIZmFSTHZMY0laRnVxbzB4bEEiLCAib3JpZ2luIjogImh0dHBzOi8vdGVzbGEtc3RhdHMucGlvbmVlcmR5bmFtaWNzLmNvbS5hdSJ9",
            "transports": [
                "internal",
                "hybrid"
            ]
        },
        "type": "public-key",
        "clientExtensionResults": [],
        "authenticatorAttachment": "cross-platform"
    }
```

**Comment by svgta1** [comment]
For the 4th option, if you wait to long, the process is canceled, it's normal. check the timeout in your parameters. The default is 300 sec (https://svgtas-organization.gitbook.io/php-webauthn/registration/create-params#timeout)

I've the same issue with the 5th. But, I don't think it's a problem of the library. The library works fine with others : 

- [x] window hello
- [x] yubikey 5
- [x] proton pass

For the 3th, and the data you receveid, you must have some other informations : 
- publicKeyAlgorithm
- publicKey
- authenticatorData

Example : 

```
{
    "id": "BP63qesxI-...",
    "rawId": "BP63qesxI-...",
    "response": {
        "attestationObject": "o2NmbXRmcGFja2VkZ2F0dFN0bXSj...",
        "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3J...",
        "transports": ["nfc", "usb"],
        "publicKeyAlgorithm": -8,
        "publicKey": "MCowBQYDK2VwAyE...",
        "authenticatorData": "pwU_KOYP8gQFgRDoKV9JAJG_LMGwWBtPT..."
    },
    "type": "public-key",
    "authenticatorAttachment": "cross-platform"
};
```

Chek the documentation there : https://svgtas-organization.gitbook.io/php-webauthn/registration/callback

I don't know enpass and can't help you to verify if there's a problem in any configuration.

**Edit :** 
may be you have to had others algorythms in the parameters for enpass. Try by adding ES256 (-8) : https://svgtas-organization.gitbook.io/php-webauthn/registration/create-params#pubkeycredparams

**Comment by mathewparet** [comment]
I have al the algorithms added already.

Also the enpass generated data doesn't have these other params. It has only the below data. Maybe we are supposed to assume some default values? 🤔 

```
{
        "id": "OXAvgXIn7w2m1DQ-udr6simqtT_DK76dZr3L6WH7hL0",
        "rawId": "OXAvgXIn7w2m1DQ-udr6simqtT_DK76dZr3L6WH7hL0",
        "response": {
            "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikrfib3PjzQH9ab0yDXhjFR6LN1Un-cXd32vJpl6_yc5tJAAAAAPOAlUB_FEnBqLOPgTsiVUEAIDlwL4FyJ-8NptQ0Prna-rIpqrU_wyu-nWa9y-lh-4S9pQECAyYgASFYIHPnYEqC9EQ9SN1cPmBRZF6ZxpsxvLUM9bvyQUQayazSIlggB1UYw1zeX7wQzmsLp5tgyCxXCWcf95I7Sr0Y1s77TOs",
            "clientDataJSON": "eyJ0eXBlIjogIndlYmF1dGhuLmNyZWF0ZSIsICJjaGFsbGVuZ2UiOiAiRk9VQXhpREh0MHQ2Sm5TQWdaQWVKZ2RIVE9vSW5CUHdBLWZnQ2xydURBcDVoejQ3M3FqSGx1MFFOMFNKV0VKamZua3pIZmFSTHZMY0laRnVxbzB4bEEiLCAib3JpZ2luIjogImh0dHBzOi8vdGVzbGEtc3RhdHMucGlvbmVlcmR5bmFtaWNzLmNvbS5hdSJ9",
            "transports": [
                "internal",
                "hybrid"
            ]
        },
        "type": "public-key",
        "clientExtensionResults": [],
        "authenticatorAttachment": "cross-platform"
    }
```

**Comment by svgta1** [comment]
No. The public key must be given. It's to verify the message given in the auth process. To explain a little, and sorry for my bad english : 
- in the register process, the authenticator give its public key and the alg it will use for the signature.
- in the auth process, the authenticator give a message and the signature of it generated with its private key. The webauthn protocol need to verify with the public key that the message and the signature are good.

without this verification, it will be very easy for a hacker to send any data to connect.

**Comment by svgta1** [comment]
Hello. Can I close the issue ?

**Comment by mathewparet** [comment]
Everything works except authenticating via my android mobile when I select authenticate using other device on the desktop.

But yeah, you can close the issue.

Thanks for your help throughout. Love the library. 

Infact, I published another library that uses this package as the base. My package just makes is specifically designed for quick addition to Laravel so that developers can integrate Passkey to their Laravel project in under 5 minutes. It uses this package as the base.

https://github.com/pioneer-dynamics/laravel-passkey - in case you want to check it out.
